branches:
  only: 
    - master
language: node_js
node_js: node
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run bootstrap
  - cd packages/client
test:
  - npm test
after_success:
  - npm run build
  - ./deploy.sh
