service:
  name: notowork-server

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: src/gql/handler.handler
    events:
      - http:
          path: api/gql
          method: get
      - http:
          path: api/gql
          method: post 
