service:
  name: aws-nodejs-typescript
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  gql:
    handler: src/gql/handler.handler
    events:
      - http:
          method: get
          path: gql
      - http:
          method: post 
          path: gql
